--concept 1 : introduction to sql server
--concept 2 : Database Architecture part1
select @@SERVERNAME
--concept 3 : Database Architecture part2
--concept 4 : Datatypes part1


create database company
go
use company
go


create table Dept
(
DeptID int primary key,
DeptName varchar(100) not null
)
go

select * from Dept;

insert into Dept values(1,'sales')
insert into Dept values(2,'marketing')
insert into Dept values(3,'technical')
insert into Dept values(4,'accounts')
insert into Dept values(5,'loans')
insert into Dept values(6,'finance')

sp_helpdb 'company'

create table Employee(
empid	int		primary key,
Empname	varchar(100)	not null,
salary	money	not null check(salary>0),
gender char(1)	not null check(gender='M' or gender='F'),
dob	datetime not null,
phone char(10) null unique,
emailID varchar(50) null unique,
passport char(10) not null unique,
DeptID int null foreign key references Dept(DeptID)
)

select * from Employee

delete  from Employee

insert into Employee values(1,'pavan', 10000, 'M', '1993-12-09','814325','pkumar.datascience@gmail.com','R5255244',3)
insert into Employee values(2,'pavanpuppala', 210000, 'M', '1994/12/09','995161','pkumar@gmail.com','R5255252',2)

sp_help 'Employee'

--concept 13

use company
go

create table product(
PID	int primary key identity(1,1),
ProdName	varchar(100)	not null,
quantity	int	null default(0),
UnitPrice	money	not null
)

select * from product
sp_help 'product'

insert into product values('pen',1000,10)
insert into product values('pencil',1100,15)
insert into product values('eraser',1000,5)
insert into product values('sketches',1000,12)
insert into product values('cabduary',800,20)

select @@IDENTITY

delete from product   --delete all rows but creates gaps

truncate table product   --delete all rows with no gaps

--default
insert into product values('lux','',20)

--explicit insert
insert into product(ProdName, UnitPrice) values('Lenovo', 120)

alter table product
add Rating tinyint

update product set Rating=2 where PID>2

--concept 14
USE MASTER
GO

CREATE DATABASE SCHOOL
GO

--drop School databse
DROP DATABASE SCHOOL
GO

--find out the schema of DB
sp_helpdb 'SCHOOL'

--change db context
USE School
GO

CREATE TABLE Course_Master
(
	CID Integer Primary Key,
	CourseName Varchar(40) NOT NULL,
	Category Char(1) NULL CHECK(Category='B' or Category='M' or Category='A'),
	Fee Smallmoney NOT NULL CHECK(Fee>0)
)
GO

--Schema of the table
sp_help 'Course_Master'

--Read the Table
SELECT * FROM [dbo].[Course_Master]

--insert the data
INSERT INTO COURSE_MASTER VALUES(101, 'AWS', 'B', 4000)

--concept 17
USE IBANK
GO

--i want all rows and all columns
SELECT * FROM AMASTER

--some columns and all rows
SELECT ACID, NAME, CBAL FROM AMASTER

--filter rows
SELECT * FROM AMASTER WHERE BRID='BR1'

--filter rows and columns
SELECT ACID, NAME FROM AMASTER WHERE BRID='BR1' AND PID='FD'

--list ACID and Name only for SB accounts and list the names in desc order
SELECT ACID, NAME FROM AMASTER WHERE PID='SB' ORDER BY NAME DESC
SELECT * FROM AMASTER WHERE PID='SB'

--will below query work or not --Ans YES
SELECT *, * from AMASTER
SELECT ACID, NAME, * FROM AMASTER
SELECT 5
SELECT 'PYTHON'
SELECT 5 FROM AMASTER
SELECT ACID, NAME, 'USD' as CURRENCY, CBAL FROM AMASTER

--concatenate two columns
SELECT ACID+ADDRESS FROM AMASTER

UPDATE AMASTER SET NAME='Pawan Puppala' WHERE ACID=102

SELECT ACID, NAME, CBAL+'INR' as CURRENCY FROM AMASTER --error
SELECT ACID, NAME, CAST(CBAL as VARCHAR)+'INR' as BALANCE FROM AMASTER
						--or
SELECT ACID, NAME, CONVERT(VARCHAR, CBAL)+'INR' as BALANCE FROM AMASTER

-- concept 18
USE IBANK
GO

SELECT * FROM AMASTER

--print Cols and constants
SELECT ACID, NAME, 'USD' AS CURRENCY, CBAL, 18 as TAX FROM AMASTER

--concatenate the columns
SELECT ACID, NAME, CBAL + 'USD' AS CURRENCY FROM AMASTER 
--Cannot convert a char value to money. The char value has incorrect syntax

SELECT ACID, NAME, 'USD'+ CAST(CBAL AS VARCHAR) AS BALANCE FROM AMASTER
SELECT ACID, NAME, 'USD'+ CONVERT (VARCHAR, CBAL) AS BALANCE FROM AMASTER

--convert function will use for date and time column
SELECT ACID, NAME, DOO, CONVERT(varchar, DOO, 2) FROM AMASTER  -- 1 to 21
SELECT ACID, NAME, DOO, CONVERT(varchar, DOO, 107) FROM AMASTER -- 101 to  131

--find out number of customers
SELECT COUNT(*) as NoOfCustomers FROM AMASTER  --or
SELECT COUNT(*) NoOfCustomers FROM AMASTER     --or
SELECT COUNT(*) as [No Of Customers] FROM AMASTER --or
SELECT COUNT(*) as 'No Of Customers' FROM AMASTER

--find out number of customers in branch 'BR1'
SELECT COUNT(*) as NoOfCustomers FROM AMASTER WHERE BRID='BR1'

--find out number of customers in branch 'BR1' and 'BR2'
SELECT COUNT(*) as NoOfCustomers FROM AMASTER WHERE BRID='BR1' or BRID='BR2'
				--or
SELECT COUNT(*) as NoOfCustomers FROM AMASTER WHERE BRID in ('BR1', 'BR2')

--findout the total	bal in branch1
SELECT SUM(CBAL) AS TotalBalance FROM AMASTER WHERE BRID='BR1'
SELECT MIN(CBAL) AS MinBalance FROM AMASTER WHERE BRID='BR1'
SELECT MAX(CBAL) AS MaxBalance FROM AMASTER WHERE BRID='BR1'
SELECT AVG(CBAL) AS AvgBalance FROM AMASTER WHERE BRID='BR1'

SELECT COUNT(*) as NoOfCustomers,
		SUM(CBAL) AS TotalBalance,
		MIN(CBAL) AS MinBalance,
		MAX(CBAL) AS MaxBalance, 
		AVG(CBAL) AS AvgBalance
FROM AMASTER 
WHERE BRID='BR1'

-- concept 19
USE IBANK
GO

--branch wise no. of customers
SELECT BRID, COUNT(*)
FROM AMASTER
GROUP BY BRID

--Branch wise no. of customers
SELECT BRID, COUNT(*) as cnt
FROM AMASTER
Where PID='SB'
GROUP BY BRID

--Product wise no. of customers
SELECT PID, COUNT(*) AS 'NO OF CUSTOMERS'
FROM AMASTER
GROUP BY PID
ORDER BY PID DESC
--ORDER BY 1 DESC

--Product wise no. of customers
SELECT PID, COUNT(*) AS 'NO OF CUSTOMERS'
FROM AMASTER
WHERE BRID='BR1'
GROUP BY PID
ORDER BY 1

-- group in group
-- Branch wise, Produt wise No. of Customers
SELECT BRID, PID, COUNT(*) AS CNT
FROM AMASTER
GROUP BY BRID, PID
ORDER BY 1

--SUM of Branch wise, Produt wise No. of Customers
SELECT BRID, PID, SUM(CBAL) AS 'TOTALBALANACE'
FROM AMASTER
GROUP BY BRID, PID

--SUM of Branch wise, Produt wise No. of Customers in year 2011
SELECT BRID, PID, SUM(CBAL) AS 'TOTALBALANACE'
FROM AMASTER
WHERE YEAR(DOO) = 2011
GROUP BY BRID, PID

--List all branches
SELECT BRID
FROM AMASTER
GROUP BY BRID  --not recommended
--Note: Group by must be usde along with aggregations

-- recommended
SELECT DISTINCT BRID FROM AMASTER

-- concept 21
SELECT GETDATE() as DT2_BUSINESS
SELECT GETDATE()-1 as DT2_YTD_BUSINESS
SELECT GETDATE()+1 as DT2_TOM_BUSINESS

--convert
SELECT CONVERT(VARCHAR, GETDATE(), 1)
SELECT CONVERT(VARCHAR, GETDATE(), 3)

SELECT DATEDIFF(DD, '2021/12/09', GETDATE()) as Days
SELECT DATEDIFF(MM, '2021/12/09', GETDATE()) as Months
SELECT DATEDIFF(WW, '2021/12/09', GETDATE()) as Weeks
SELECT DATEDIFF(QQ, '2021/12/09', GETDATE()) as Quarters
SELECT DATEDIFF(HOUR, '2021/12/09', GETDATE()) as Quarters

--what is my age
SELECT DATEDIFF(YY, '1994/12/09', GETDATE()) as Age

--what is the age of each account
SELECT ACID, NAME, CBAL, DOO, DATEDIFF(YY, DOO, GETDATE()) AS AgeOfAccount 
FROM AMASTER 

--List out the accounts, opened in the current year
SELECT ACID, NAME, CBAL, DOO, DATEDIFF(YY, DOO, GETDATE()) AS AgeOfAccount 
FROM AMASTER
WHERE DateDiff(YY, doo, getdate())=0

--List out the accounts, opened in the Last year
SELECT ACID, NAME, CBAL, DOO, DATEDIFF(YY, DOO, GETDATE()) AS AgeOfAccount 
FROM AMASTER
WHERE DateDiff(YY, doo, getdate())=1

--List out the accounts, opened in the current month
SELECT ACID, NAME, CBAL, DOO, DATEDIFF(YY, DOO, GETDATE()) AS AgeOfAccount 
FROM AMASTER
WHERE DateDiff(MM, doo, getdate())=0

--List out the accounts, opened today
SELECT ACID, NAME, CBAL, DOO, DATEDIFF(YY, DOO, GETDATE()) AS AgeOfAccount 
FROM AMASTER
WHERE DateDiff(DD, doo, getdate())=0

--How many Customers opened accounts in last 3years
SELECT * FROM AMASTER WHERE DATEDIFF(YY, DOO, GETDATE())<=3

SELECT DATEPART(YY, GETDATE()) AS Year
SELECT DATEPART(MM, GETDATE()) AS Month
SELECT DATEPART(DD, GETDATE()) AS Day

--year wise , No of accounts opened
SELECT DATEPART(YY, DOO) AS YearNo, COUNT(*) as CNT
FROM AMASTER
GROUP BY DATEPART(YY, DOO)

--List Customers who opened acounts in 2011
SELECT ACID, NAME, CBAL, DATEPART(YY, DOO) AS YearNo
FROM AMASTER
WHERE DATEPART(YY, DOO) = 2011

--List Customers who opened acounts in APRIL 2011
SELECT ACID, NAME, CBAL, DOO, DATEPART(YY, DOO) AS YearNo
FROM AMASTER
WHERE DATEPART(YY, DOO) = 2011 and DATEPART(MM, DOO) = 4

--List Customers who opened acounts in 10th APRIL 2011
SELECT ACID, NAME, CBAL, DOO, DATEPART(YY, DOO) AS YearNo
FROM AMASTER
WHERE DATEPART(YY, DOO) = 2011 and DATEPART(MM, DOO) = 4 and DATEPART(DD, DOO)=10


SELECT DATENAME(YY, GETDATE()) AS Year
SELECT DATENAME(MM, GETDATE()) AS Month
SELECT DATENAME(DD, GETDATE()) AS Day

--concept 22
USE IBANK
GO

SELECT ACID, NAME, DOO, 
	DATEPART(YY, DOO) AS YearNO,
	DATEPART(MM, DOO) AS MonthNO,
	DATEPART(DD, DOO) AS DayNO,
	DATEPART(WW, DOO) AS WeekNO,
	DATEPART(QQ, DOO) AS QtrNO,
	DATENAME(YY, DOO) AS YearName,
	DATENAME(MM, DOO) AS MontName,
	DATENAME(DD, DOO) AS DaName,
	DATENAME(WW, DOO) AS WeekName,
	DATENAME(DW, DOO) AS WeekofdayName
FROM AMASTER

SELECT ACID, NAME, DOO, 
	YEAR(DOO) AS YearNO,
	MONTH(DOO) AS MonthNO,
	DAY(DOO) AS DayNO
FROM AMASTER


--Total Balance year wise, Quarter Wise , Month Wise
SELECT DATEPART(YY, DOO) as YNO, 
	   'Q'+CAST(DATEPART(QQ, DOO) as varchar) as QNO, 
	    DATENAME(MM, DOO) as MName, 
		SUM(CBAL) as TOTALBALANCE
FROM AMASTER
group by DATEPART(YY, DOO), DATEPART(QQ, DOO), DATENAME(MM, DOO)

--Total Balance year wise, Quarter Wise , Month Wise for year =2011 and brid = br1
SELECT DATEPART(YY, DOO) as YNO, 
	   'Q'+CAST(DATEPART(QQ, DOO) as varchar) as QNO, 
	    DATENAME(MM, DOO) as MName, 
		SUM(CBAL) as TOTALBALANCE
FROM AMASTER
WHERE BRID='BR1' and DATEPART(YY, DOO) = 2011
group by DATEPART(YY, DOO), DATEPART(QQ, DOO), DATENAME(MM, DOO)

SELECT DATEADD(DD, -40, GETDATE())
SELECT DATEADD(MM, -8, GETDATE())
SELECT DATEADD(YY, -28, GETDATE())

--EMI date for every month
SELECT ACID,NAME,CBAL,DOO, DATEADD(MM, 1, DOO) AS DUEDATE
FROM AMASTER

--Last day of the provided month
SELECT EOMONTH(GETDATE())

SELECT ACID,NAME,CBAL,DOO AS PAID, EOMONTH(DOO) AS DUEDATE
FROM AMASTER

--concept 23 Having Clause & Into keyword & Temp tables
SELECT * FROM AMASTER

SELECT TOP(5) * FROM AMASTER  --or
SELECT TOP(5) ACID, NAME, CBAL FROM AMASTER
SELECT TOP(5) * FROM AMASTER ORDER BY CBAL DESC

--Latest Records
SELECT TOP(5) * FROM AMASTER ORDER BY DOO DESC

SELECT TOP(5) PERCENT NAME, CBAL FROM AMASTER  --62 rows*5 rows/100
SELECT 62*5/100

--Find out the Month wise no. of accounts opened in the year 2011
SELECT DATEPART(MM, DOO) as MonthNo,DATENAME(MM, DOO) as MonthName, COUNT(*) as CNT
FROM AMASTER
WHERE DATEPART(YY, DOO) = 2011
GROUP BY DATEPART(MM, DOO), DATENAME(MM, DOO)
ORDER BY 1 ASC

--Product wise no. of customers in branch BR1
SELECT PID, COUNT(*) as CNT	 --4th aggr, 5th display
FROM AMASTER                 --1
WHERE BRID='BR1'			 --2
GROUP BY PID				 --3

SELECT PID, COUNT(*) as CNT	
FROM AMASTER                 
WHERE BRID='BR1'			 
GROUP BY PID				 
HAVING COUNT(*)>5

--Branch wise total amount in the month of january
--provide the details if total amount exceeds 5000/-
SELECT BRID, SUM(CBAL) as TOTAL
FROM AMASTER
WHERE DATEPART(MM, DOO)=1
GROUP BY BRID
HAVING SUM(CBAL)>5000

SELECT * FROM TMASTER

SELECT BRID, SUM(TXNAMT) as TOTAL
FROM TMASTER
WHERE BRID IN ('BR1','BR2')
GROUP BY BRID
HAVING SUM(TXNAMT)>1700000

--branch wise TOTAL AMOUNT in the month of FEB
--Provide details if branch=BR1
SELECT BRID, SUM(CBAL) as CNT
FROM AMASTER
WHERE DATEPART(MM,DOO)=2                 --not recommended
GROUP BY BRID
HAVING BRID='BR1'

SELECT BRID, SUM(CBAL) as CNT
FROM AMASTER
WHERE DATEPART(MM,DOO)=2 AND BRID='BR3'  --recommended
GROUP BY BRID

SELECT BRID, SUM(CBAL) as TOTAL into BRANCHWISEBAL
FROM AMASTER
WHERE DATEPART(MM,DOO)=3
GROUP BY BRID

SELECT * FROM BRANCHWISEBAL


--Last year Nov and Dec month sales
SELECT BRID, SUM(CBAL) as TOTAL
FROM AMASTER
WHERE DATEDIFF(YY, DOO, GETDATE())=1 AND DATEPART(MM, DOO) in (11,12)
GROUP BY BRID

SELECT BRID, SUM(CBAL) as TOTAL into #BRANCHWISEBAL
FROM AMASTER
WHERE DATEPART(MM,DOO)=3
GROUP BY BRID

SELECT * FROM #BRANCHWISEBAL

DROP TABLE #BRANCHWISEBAL

--how to create a blank table
SELECT * INTO BLANKTABLE FROM AMASTER WHERE 1 = 2

SELECT * FROM BLANKTABLE

--concept 24 inner and outer join
USE IBANK
GO

SELECT * FROM AMASTER
SELECT * FROM TMASTER
SELECT * FROM PMASTER

SELECT *
FROM AMASTER
INNER JOIN TMASTER ON AMASTER.ACID = TMASTER.ACID

SELECT *
FROM AMASTER
INNER JOIN TMASTER ON AMASTER.ACID = TMASTER.ACID
INNER JOIN PMASTER ON AMASTER.PID = PMASTER.PID

--concept 25 cross join
USE IBANK
GO

--List Names of the Account Holders and their product names
SELECT * FROM AMASTER
SELECT * FROM PMASTER

SELECT NAME, PNAME 
FROM AMASTER INNER JOIN PMASTER 
ON AMASTER.PID = PMASTER.PID

--Find out customer Name wise, txn type wise, number of Transactions
SELECT * FROM TMASTER

SELECT NAME,TXNTYPE, COUNT(*) AS NOOFTXNS
FROM AMASTER INNER JOIN TMASTER
ON AMASTER.ACID = TMASTER.ACID
GROUP BY NAME, TXNTYPE

--Last Month
SELECT NAME,TXNTYPE, COUNT(*) AS NOOFTXNS
FROM AMASTER INNER JOIN TMASTER
ON AMASTER.ACID = TMASTER.ACID
WHERE DATEDIFF(MM, DOT, GETDATE())=1
GROUP BY NAME, TXNTYPE

--Last Year
SELECT NAME,TXNTYPE, COUNT(*) AS NOOFTXNS
FROM AMASTER INNER JOIN TMASTER
ON AMASTER.ACID = TMASTER.ACID
WHERE DATEDIFF(YY, DOT, GETDATE())=1
GROUP BY NAME, TXNTYPE

--in year 2011
SELECT NAME,TXNTYPE, COUNT(*) AS NOOFTXNS
FROM AMASTER INNER JOIN TMASTER
ON AMASTER.ACID = TMASTER.ACID
WHERE DATEPART(YY, DOT)=2011
GROUP BY NAME, TXNTYPE


--List Names of the account holder who deposited cash and their product names
SELECT DISTINCT NAME, PNAME 
FROM AMASTER A INNER JOIN TMASTER T ON A.ACID = T.ACID
INNER JOIN PMASTER P ON A.PID = P.PID
WHERE TXNTYPE='CD'

--Left Join
SELECT *
FROM AMASTER A LEFT JOIN TMASTER T ON A.ACID = T.ACID

--unmatched data from left table
SELECT *
FROM AMASTER A LEFT JOIN TMASTER T ON A.ACID = T.ACID
WHERE TNO IS NULL

SELECT A.ACID, NAME
FROM AMASTER A LEFT JOIN TMASTER T ON A.ACID = T.ACID
WHERE TNO IS NULL

--concept 26 self join
USE IBANK
GO

--self referential table
CREATE TABLE EMP
(
	EID INT PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	MID INT NULL FOREIGN KEY REFERENCES EMP(EID)
)

INSERT into emp values(1, 'Narasimha', Null)
INSERT into emp values(2, 'Naga', 1)
INSERT into emp values(3, 'Sharada', 1)
INSERT into emp values(4, 'pawan', 2)
INSERT into emp values(5, 'Kiran', 3)

SELECT * FROM EMP

SELECT emp1.NAME as empName, emp2.NAME as Boss 
FROM EMP as emp1 join EMP as emp2 on emp2.EID = emp1.MID

SELECT emp1.NAME as empName, emp2.NAME as Boss 
FROM EMP as emp1 left join EMP as emp2 on emp2.EID = emp1.MID


--union
CREATE TABLE CUSTOMER
(
	ID INT PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	ADDRESS VARCHAR(10) NOT NULL
)

CREATE TABLE VENDOR
(
	ID INT PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	ADDRESS VARCHAR(10) NOT NULL
)

INSERT into CUSTOMER values(1, 'HARI G', 'JP NAGAR')
INSERT into CUSTOMER values(2, 'VIMAL', 'RV ROAD')
INSERT into CUSTOMER values(3, 'JOHN R', 'KK ROAD')

INSERT into VENDOR values(1, 'JOHN R', 'KK ROAD')
INSERT into VENDOR values(2, 'MERCY', 'JP NAGAR')
INSERT into VENDOR values(3, 'HARI G', 'JP NAGAR')
INSERT into VENDOR values(4, 'HARI G', 'JP NAGAR')

SELECT NAME,ADDRESS FROM CUSTOMER
UNION
SELECT NAME,ADDRESS FROM VENDOR

SELECT NAME,ADDRESS FROM CUSTOMER
UNION ALL
SELECT NAME,ADDRESS FROM VENDOR

SELECT * FROM AMASTER WHERE NAME LIKE 'p%'
SELECT * FROM AMASTER WHERE NAME LIKE '%r'
SELECT * FROM AMASTER WHERE NAME LIKE '%av%'
SELECT * FROM AMASTER WHERE NAME LIKE '_a%'
SELECT * FROM AMASTER WHERE NAME LIKE 'a__%'
SELECT * FROM AMASTER WHERE NAME LIKE 'p%n'

SELECT ACID, NAME, ISNULL(CBAL, 0) AS BALANCE FROM AMASTER

USE EMP
GO

SELECT COALESCE(FIRSTNAME, MIDDLENAME, LASTNAME) AS EMPLOYEE FROM EMP

SELECT ISNULL(FIRSTNAME,'')+ISNULL(MIDDLENAME,'')+ISNULL(LASTNAME,'')  AS FULLNAME FROM EMP
                  --OR
SELECT CONCAT(FIRSTNAME, MIDDLENAME, LASTNAME) AS FULLNAME FROM EMP


-----------------------27. String Functions-----------------------------
USE IBANK 
GO

SELECT ACID, NAME,
UPPER(NAME) as UPR_NAME,
LOWER(NAME) as LWR_NAME,
LEFT(NAME, 4) as FIRST_4CHAR,
RIGHT(NAME, 4) as LAST_4CHAR,
LEN(NAME) as LENGTH_NAME,
REVERSE(NAME) as REVERSE_NAME,
LTRIM(NAME) as TRIM_LEFT,
RTRIM(NAME) as TRIM_RIGHT,
TRIM(NAME) as TRIM_NAME
FROM AMASTER

CREATE TABLE EMPLOYEE
(
CID			INT				PRIMARY KEY,
NAME		VARCHAR(100)	NOT NULL,
PHONENO		CHAR(10)		NOT NULL CHECK(LEN(PHONENO) = 10) UNIQUE,
DOB			DATETIME		NOT NULL CHECK(DATEDIFF(YY, DOB, GETDATE())>=21 AND DATEDIFF(YY, DOB, GETDATE())<=58)
)

SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES(1, 'PAVAN', '8143256414', '1994/12/09')
INSERT INTO EMPLOYEE VALUES(2, 'KUMAR', '9951612245', '1993/11/02')
INSERT INTO EMPLOYEE VALUES(3, 'JHANSI', '9951612000', '1994/12/09')
INSERT INTO EMPLOYEE VALUES(1, 'PAVAN', '8143256414', '1994/12/09')


SELECT 
	ACID,
	NAME,
	SUBSTRING(NAME, 1, 4) AS NAME,
	REVERSE(NAME) AS REVERSE_NAME,
	SUBSTRING(REVERSE(NAME),1,5) AS SUB_NAME,
	REVERSE(SUBSTRING(REVERSE(NAME),1,5)) AS REVERSE_SUBNAME
FROM  AMASTER 

SELECT 
	ACID,
	NAME,
	STUFF(NAME, 1,3,'USA') AS NAME
FROM  AMASTER

SELECT 
	ACID,
	NAME,
	REPLACE(NAME, 'ee', 'i') as NAME
FROM  AMASTER


SELECT CHARINDEX(' ','Hello World')  --6
SELECT CHARINDEX('i','iiHello World') --1
SELECT CHARINDEX('i','iiHello iWorld', 3) --9

SELECT PATINDEX('%hello%', 'HI hello pavan how are you')  --4

-----------28. string_agg()--------------
CREATE TABLE EMPL
(
	EID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL
)

insert into EMPL values(1, 'pavan')
insert into EMPL values(1, 'kumar')
insert into EMPL values(2, 'jhansi')
insert into EMPL values(2, 'sharada')
insert into EMPL values(3, 'puppala')

SELECT * FROM EMPL

SELECT EID, STRING_AGG(name, ',') as EmpName 
FROM EMPL
GROUP BY EID

SELECT NAME, CBAL 
FROM AMASTER 
WHERE CBAL BETWEEN 10000 AND 50000

SELECT * 
FROM AMASTER
WHERE DATEPART(YY, DOO) BETWEEN 2010 AND 2012

SELECT  ACID,
		NAME,
		CBAL,
		CASE
			WHEN CBAL < 10000 THEN 'SILVER'
			WHEN CBAL BETWEEN 10000 AND 50000 THEN 'GOLD'
			ELSE 'PLATINUM'
		END AS CUSTOMER
FROM AMASTER

SELECT EID,
	   EmpName = 
	   CASE
			WHEN Gender = 'M' THEN 'Mr.'+Name
			ELSE 'Ms.'+Name
		END
FROM EMP



-----------29. sub queries--------------
SELECT NULLIF(4,4) RESULTS

SELECT NULLIF(-4,-4) RESULTS

SELECT NULLIF(8,4) RESULTS

SELECT NULLIF(2,4) RESULTS

SELECT ACID, NAME, NULLIF(CBAL, UBAL) AS BALANCE
FROM AMASTER

DECLARE @V1 BIT = NULL
DECLARE @V2 INT = NULL
DECLARE @V3 NUMERIC(18,2) = 455.12

SELECT COALESCE(@V1, @V2, @V3)
SELECT ISNULL(@V1, @V3)
SELECT ISNULL(@V2, @V3)

USE IBANK 
GO

--invalid
SELECT MAX(CBAL)
FROM AMASTER

--invalid
SELECT NAME, MAX(CBAL)
FROM AMASTER
GROUP BY NAME

SELECT * 
FROM AMASTER 
WHERE CBAL = (SELECT MAX(CBAL) FROM AMASTER)

-----------30. correlated sub queries----------------

SELECT ACID, NAME, CBAL-(SELECT AVG(CBAL) FROM AMASTER) AS DIFF 
FROM AMASTER

SELECT * FROM AMASTER WHERE CBAL=(
	SELECT MAX(CBAL) AS SECONDHIGHEST
	FROM AMASTER
	WHERE CBAL<(SELECT MAX(CBAL) FROM AMASTER)
)

SELECT * FROM AMASTER WHERE CBAL=(
	SELECT MAX(CBAL) AS SECONDHIGHEST
	FROM AMASTER
	WHERE CBAL not in(SELECT MAX(CBAL) FROM AMASTER)
)

-----10th highest balance

--sort the cbal in desc and distinct and top10 and min and name
SELECT * FROM AMASTER WHERE CBAL =(
	SELECT MIN(CBAL) FROM AMASTER WHERE CBAL IN (
		SELECT DISTINCT TOP 10 CBAL FROM AMASTER ORDER BY CBAL DESC
		)
)

SELECT * FROM AMASTER AM WHERE EXISTS 
(SELECT * FROM TMASTER TM WHERE AM.ACID = TM.ACID)

--------------31. system tables------------
USE IBANK
GO
--To check the number of tables present in a database
SELECT * FROM SYS.TABLES

SELECT COUNT(*) FROM SYS.TABLES

SELECT * FROM SYS.COLUMNS

SELECT * FROM SYS.COLUMNS where object_id=165575628

--Find out number of columns in table
SELECT COUNT(*) FROM SYS.COLUMNS WHERE OBJECT_ID=165575628

SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID=(
SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME='AMASTER'
)

SELECT * FROM SYS.TABLES WHERE OBJECT_ID=165575628
SELECT * FROM SYS.columns WHERE NAME='CBAL'

--Identify the tables where column cbal present
SELECT B.NAME AS TABLENM, A.NAME AS COLNM  
FROM SYS.COLUMNS A JOIN SYS.TABLES B 
ON A.OBJECT_ID=B.OBJECT_ID 
WHERE A.NAME='CBAL'

--check emp tables exits or not
IF EXISTS ( SELECT * FROM SYS.TABLES WHERE NAME='EMP' )
	DROP TABLE EMP
GO

CREATE TABLE EMP(
	EID INT PRIMARY KEY,
	ENAME VARCHAR(100) 
)
GO

SELECT * FROM SYS.PROCEDURES
SELECT * FROM SYS.TRIGGERS

SELECT 'DROP TABLE '+NAME FROM SYS.TABLES

-------------------31. derived tables------------------

USE IBANK 
GO

SELECT * FROM (SELECT * FROM AMASTER)q

----joins------
SELECT A.ACID, NAME, COUNT(*) NoOfTxns 
FROM AMASTER A JOIN TMASTER T 
ON A.ACID=T.ACID
WHERE DATEPART(YY, DOT) =2011
GROUP BY A.ACID, NAME


----Derived tables----------
SELECT NAME, A.ACID, NOOFTXNS 
FROM AMASTER A 
JOIN (
	SELECT ACID, COUNT(*) NOOFTXNS 
	FROM TMASTER 
	WHERE DATEPART(YY, DOT) =2011
	GROUP BY ACID
	)K
ON A.ACID=K.ACID

create table customers(
	DOS datetime primary key,
	CUSTOMER VARCHAR(100) not null,
	SALESAMOUNT money null
)

SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS VALUES('C1', '12-1-2022',  1000)
INSERT INTO CUSTOMERS VALUES('C2','20-1-2022',  1200)
INSERT INTO CUSTOMERS VALUES('7/2/2022', 'C3', 500)
INSERT INTO CUSTOMERS VALUES('15/2/2022', 'C1', 300)
INSERT INTO CUSTOMERS VALUES('21/2/2022', 'C4', 750)
INSERT INTO CUSTOMERS VALUES('2/3/2022', 'C5', 1500)
INSERT INTO CUSTOMERS VALUES('22/3/2022', 'C6', 8000)
INSERT INTO CUSTOMERS VALUES('25/3/2022', 'C4', 7000)

drop table customers
delete from customers

create table customers(
CUSTOMER	varchar(40)		primary key,
DOS	datetime not null,
SALESAMOUNT	money	not null
)

select * from Employee

delete  from Employee

insert into Employee values(1,'pavan', 10000, 'M', '1993-12-09','814325','pkumar.datascience@gmail.com','R5255244',3)
insert into Employee values(2,'pavanpuppala', 210000, 'M', '1994/12/09','995161','pkumar@gmail.com','R5255252',2)

SELECT DATENAME(MM, MINDATE) AS MONTHNME, COUNT(*) AS CNT, DATEPART(MM, MINDATE) AS MONTHNUM
FROM
(
	SELECT CUSTOMER, MIN(DOS) AS MINDATE
	FROM CUSTOMERS
	GROUP BY CUSTOMER
)Q
GROUP BY DATENAME(MM, MINDATE), DATEPART(MM, MINDATE)
ORDER BY MONTHNUM ASC


-- Find Employees with Salary Higher than their Department Average
CREATE TABLE EMPINFO(
	EID INT PRIMARY KEY,
	EMPNAME VARCHAR(100) NOT NULL,
	SALARY MONEY NOT NULL,
	DEPTNAME VARCHAR(25) NOT NULL
)



INSERT INTO EMPINFO VALUES(1, 'JOHN', 10000, 'HR')
INSERT INTO EMPINFO VALUES(2, 'GIRISH', 12000, 'SALES')
INSERT INTO EMPINFO VALUES(3, 'MANNAT', 8000, 'SALES')
INSERT INTO EMPINFO VALUES(4, 'SALMAN', 14000, 'HR')
INSERT INTO EMPINFO VALUES(5, 'RATAN', 9000, 'HR')
INSERT INTO EMPINFO VALUES(6, 'PETER', 11000, 'SALES')

SELECT * FROM EMPINFO

SELECT * FROM EMPINFO E1 JOIN 
(
SELECT DEPTNAME, AVG(SALARY) AS AVGSAL
FROM EMPINFO
GROUP BY DEPTNAME
) E2
ON E1.DEPTNAME = E2.DEPTNAME
where SALARY>AVGSAL

------33. cube and rollup operators-----

SELECT * FROM ITEM

--total quantity
SELECT SUM(QNTY) as TOTAL FROM ITEM

--total quantity only for chairs
SELECT SUM(QNTY) as TOTAL FROM ITEM WHERE ITEMNAME='chair'

--total quantity only for table
SELECT SUM(QNTY) as TOTAL FROM ITEM WHERE ITEMNAME='table'

--total quantity only for black colors
SELECT SUM(QNTY) as TOTAL FROM ITEM WHERE COLOR='black'

--total quantity only for red colors
SELECT SUM(QNTY) as TOTAL FROM ITEM WHERE COLOR='red'

--item wise, color wise, total quantity
SELECT ITEMNAME, COLOR, SUM(QNTY) as TOTAL 
FROM ITEM
GROUP BY ITEMNAME, COLOR

--item wise, color wise, total quantity
SELECT ITEMNAME, COLOR, SUM(QNTY) as TOTAL 
FROM ITEM
GROUP BY ITEMNAME, COLOR WITH CUBE

--item wise, color wise, total quantity
SELECT ITEMNAME, COLOR, SUM(QNTY) as TOTAL 
FROM ITEM
GROUP BY ITEMNAME, COLOR WITH ROLLUP

-----------34. rank functions----------------
USE IBANK 
GO

--ROW number()
SELECT ACID, NAME, CBAL, BRID,
		ROW_NUMBER() OVER (ORDER BY ACID) AS RNO FROM AMASTER

-- 5th row
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
					ROW_NUMBER() OVER (ORDER BY ACID) AS RNO FROM AMASTER
			)as K
WHERE RNO=5

-----between values
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
						ROW_NUMBER() OVER (ORDER BY ACID) AS RNO FROM AMASTER
			)as K
WHERE RNO BETWEEN 3 AND 6

---Using partition by
SELECT ACID, NAME, CBAL, BRID,
						ROW_NUMBER() OVER (PARTITION BY BRID ORDER BY ACID) AS RNO FROM AMASTER

SELECT ACID, NAME, CBAL, BRID,
						ROW_NUMBER() OVER (PARTITION BY BRID ORDER BY ACID DESC) AS RNO FROM AMASTER

----For every branch first customer 
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
						ROW_NUMBER() OVER (PARTITION BY BRID ORDER BY ACID) AS RNO FROM AMASTER
			)as K
WHERE RNO=1

----For every branch 5th customer 
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
						ROW_NUMBER() OVER (PARTITION BY BRID ORDER BY ACID) AS RNO FROM AMASTER
			)as K
WHERE RNO%5 = 0

--alternate
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
						ROW_NUMBER() OVER (PARTITION BY BRID ORDER BY ACID) AS RNO FROM AMASTER
			)as K
WHERE RNO % 2 = 0

--rank()
SELECT ACID, NAME, CBAL, BRID,
						RANK() OVER ( ORDER BY CBAL DESC) AS RNO,
						DENSE_RANK() OVER ( ORDER BY CBAL DESC) AS Dn_RNO 
						FROM AMASTER

---10th highest balance
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
						DENSE_RANK() OVER ( ORDER BY CBAL DESC) AS Dn_RNO  FROM AMASTER
			)as K
WHERE Dn_RNO = 10

--branch wise highest balance
SELECT * 
FROM (
				SELECT ACID, NAME, CBAL, BRID,
						DENSE_RANK() OVER (PARTITION BY BRID ORDER BY CBAL DESC) AS Dn_RNO  FROM AMASTER
			)as K
WHERE Dn_RNO = 1


SELECT ACID, NAME, CBAL, BRID,
						NTILE(4) OVER ( ORDER BY ACID ASC) AS GrpNo  FROM AMASTER

SELECT ACID, NAME, CBAL, BRID,
						NTILE(4) OVER ( PARTITION BY BRID  ORDER BY ACID ASC) AS GrpNo  FROM AMASTER

select 64/4


--5th row using CTE
with accdata
as (
				SELECT ACID, NAME, CBAL, BRID,
					ROW_NUMBER() OVER (ORDER BY ACID) AS RNO FROM AMASTER
			)
select * from accdata WHERE RNO=5

;with accdata
as (
				SELECT ACID, NAME, CBAL, BRID,
					ROW_NUMBER() OVER (ORDER BY ACID) AS RNO FROM AMASTER
			)
select * from accdata WHERE RNO=10

----------Find out the branch which has highest number of customers

SELECT BRID, COUNT(*) as CNT
FROM AMASTER
GROUP BY BRID

SELECT max(CNT) 
FROM (
	SELECT BRID, COUNT(*) as CNT
	FROM AMASTER
	GROUP BY BRID
)k

select BRID
FROM (
			SELECT BRID, COUNT(*) as CNT
			FROM AMASTER
			GROUP BY BRID
) as k
where CNT = (
							SELECT max(CNT) 
							FROM (
											SELECT BRID, COUNT(*) as CNT
											FROM AMASTER
											GROUP BY BRID
										)k
)


WITH K 
AS
(
	SELECT BRID, COUNT(*) AS CNT
	FROM AMASTER
	GROUP BY BRID
)
SELECT * FROM K WHERE CNT = (SELECT MAX(CNT) FROM K)

SELECT BRID, COUNT(*) AS CNT
INTO #K
FROM AMASTER
GROUP BY BRID

SELECT * FROM #K


CREATE TABLE STUDENT
(
 NAME VARCHAR(100)
)

INSERT INTO STUDENT VALUES('PAVAN')
INSERT INTO STUDENT VALUES('PAVAN')
INSERT INTO STUDENT VALUES('KUMAR')
INSERT INTO STUDENT VALUES('KUMAR')
INSERT INTO STUDENT VALUES('KUMAR')
INSERT INTO STUDENT VALUES('PUPPALA')
INSERT INTO STUDENT VALUES('JHAN')

SELECT * FROM STUDENT

SELECT NAME, COUNT(*) AS CNT FROM STUDENT
GROUP BY NAME
HAVING COUNT(*)>1

SELECT DISTINCT NAME FROM STUDENT

;WITH DUP
AS
(
	SELECT NAME,
				ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY NAME ASC) AS RNO
				FROM STUDENT
)
DELETE FROM DUP WHERE RNO >1

--window functions
SELECT ACID, NAME , CBAL, SUM(CBAL) OVER (ORDER BY ACID ASC) AS RUNNING_TOTAL
FROM AMASTER

SELECT ACID, NAME , CBAL ,BRID,  SUM(CBAL) OVER (PARTITION BY BRID ORDER BY ACID ASC) AS RUNNING_TOTAL
FROM AMASTER

-------36. merge statement to perform incremental loading
if Exists (select * from sys.databases where name='MergeDB')
drop database MergeDB
go

USE MergeDB
GO

CREATE TABLE MERGESTUDENT
(
	EID  INT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	SALARY MONEY NOT NULL
)



insert into MERGESTUDENT values(1, 'pawan', 1000)
insert into MERGESTUDENT values(2, 'kumar', 2000)
--insert into MERGESTUDENT values(1, 'pawan', 1000)
--insert into MERGESTUDENT values(1, 'pawan', 1000)
--insert into MERGESTUDENT values(1, 'pawan', 1000)
--insert into MERGESTUDENT values(1, 'pawan', 1000)
--insert into MERGESTUDENT values(1, 'pawan', 1000)

CREATE TABLE DestinationSTUDENT
(
	EID  INT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	SALARY MONEY NOT NULL
)

select * from MERGESTUDENT
select * from DestinationSTUDENT

delete from  MERGESTUDENT
delete from DestinationSTUDENT

merge DestinationSTUDENT as D
using MERGESTUDENT as s
on d.eid= s.eid

when not matched by target
then
insert (eid, name, salary) values(s.eid, s.name, s.salary )

when matched and d.name<> s.name or d.salary <> s.salary
then
update
set d.name= s.name	, d.salary=s.salary

when not matched by source
then delete;



